### ISSUE TITLE
Ternary Operators

### ISSUE THREAD

**Issue by mileszs** [getfretless/ruby#1]
The guide says:

> Avoid the ternary operator (?:) except in cases where all expressions are extremely trivial. However, do use the ternary operator(?:) over if/then/else/end constructs for single line conditionals.

I somewhat disagree with the second point. I prefer if/then/else/end constructs over the more traditional ternary operator when need if/else on a single line. (Agree with avoiding it as often as possible.)

What do you guys think?

**Comment by dstrus** [comment]
In general, I agree with your assessment. I have some preference for the ternary operator for inline conditionals in Rails views, but almost nowhere else. Even in Rails views, a helper method is virtually always preferable to using the ternary operator.

**Comment by unixmonkey** [comment]
I'd rather see a ternary than a single line `if then else end`

I think because if I see an `if` or `while` or something like that, I start looking for the inner body, and don't expect to see it on the same line.

Also, inline `if then else end` statements sometimes needs semicolons, and removes a bit of the terseness you get from a single line expression because it is now several characters longer, so you might as well go ahead and add some line breaks.

I think most linters will also go ahead and ding you if you try to assign the result of an expression like:

``` ruby
foo = if thing.present? then 'cool' else 'lame' end
```

but have no problem with

``` ruby
foo = thing.present? ? 'cool' : 'lame'
```

As a teaching thing, I definitely get the allure of just ignoring ternary, as it has a weird syntax that isn't descriptive of what it does, but it is so common and cross-language, I accept that they exist and use them where they feel most appropriate.

**Comment by dstrus** [comment]
I was misinterpreting "single-line conditionals" in the original text. Your interpretation is correct, @unixmonkey. Single-line conditionals with an `else` clause are gross. Generally, I would avoid them one of the following ways: a) change to a multi-line conditional, b) extract to a method, c) use a ternary.

**Comment by mileszs** [comment]
Totally fair; I'm on-board with those thoughts. I don't feel super-strongly about this one.

As for terseness, I do find the ternary operator to be overly terse to the point of obfuscation - even though nearly every language I've ever used featured the ternary operator. All kings in Europe prior to 1066 gruesomely killed political rivals given the hint of an excuse, so William the Conqueror might as well have killed his political rivals given the hint of an excuse. 😉 CoffeeScript doesn't have the ternary, which sorta makes me happy. If Ruby didn't require the `end` in the if/then/else/end, I'd probably be more anti-ternary. 

CoffeeScript: `if true then 5 else 10`

As for linters, I don't care much what third-party linters like or dislike, so much as I care that we decide what we like or dislike _and why_. 

Thanks for commenting, dudes!
